### PR TITLE
Handling PG exceptions

### LINKED ISSUE #193: Handling PG exceptions
From #69:

> I'd also appreciate if there were an error_handling function which I could define to 'rescue' any errors inside logidze without failing the transaction. I do this for a number of my other function, e.g.

```sql
  EXCEPTION
    -- https://www.postgresql.org/docs/11/errcodes-appendix.html
    -- https://www.postgresql.org/docs/11/plpgsql-control-structures.html#PLPGSQL-ERROR-TRAPPING
    WHEN DEADLOCK_DETECTED OR QUERY_CANCELED OR LOCK_NOT_AVAILABLE THEN
      RAISE WARNING 'APP_NOTICE: DATABASE ERROR DETECTED: function % on invoice_ids %. running: %\n', fn_name, invoice_ids, current_query();
      GET STACKED DIAGNOSTICS
          _db_err_sql_state := RETURNED_SQLSTATE,
          _db_err_message := MESSAGE_TEXT,
          _db_err_detail := PG_EXCEPTION_DETAIL,
          _db_err_hint := PG_EXCEPTION_HINT,
          _db_err_context := PG_EXCEPTION_CONTEXT;

      IF COALESCE(current_setting('logidze.meta', true), '') <> '' THEN
        _db_err_responsible_id := current_setting('logidze.meta')::text;
      END IF;

      INSERT INTO database_errors (
        sql_state, message, detail, hint, context,
        fn_name, fn_args, current_query, responsible_id
      ) VALUES (
        _db_err_sql_state, _db_err_message, _db_err_detail, _db_err_hint, _db_err_context,
        fn_name, quote_literal(invoice_ids::text), current_query()::text, _db_err_responsible_id
      );
```

### PR DESCRIPTION
**Pull request by skryukov**
This adds:
- handler for the `NUMERIC_VALUE_OUT_OF_RANGE` exception
- `logidze_capture_exception(error_data jsonb)` function which allows to add custom behavior on exception

Closes #193

### CODE REVIEW

File: lib/generators/logidze/install/functions/logidze_logger.sql [hunk 1]
```diff
@@ -89,11 +89,25 @@ CREATE OR REPLACE FUNCTION logidze_logger() RETURNS TRIGGER AS $body$
       changes := '{}';
 
       IF (coalesce(current_setting('logidze.full_snapshot', true), '') = 'on') THEN
-        changes = hstore_to_jsonb_loose(hstore(NEW.*));
+        BEGIN
+          changes = hstore_to_jsonb_loose(hstore(NEW.*));
+        EXCEPTION
+          WHEN NUMERIC_VALUE_OUT_OF_RANGE THEN
```
Comment (skryukov) [inline lib/generators/logidze/install/functions/logidze_logger.sql:95]: It's also possible to use the `OTHERS` condition (_The special condition name OTHERS matches every error type except QUERY_CANCELED and ASSERT_FAILURE._), don't really sure.

Comment (palkan) [reply lib/generators/logidze/install/functions/logidze_logger.sql:95]: I think, NUMERIC_VALUE_OUT_OF_RANGE is enough here. Unless we know which else could go wrong during hstore conversion.

File: lib/generators/logidze/install/functions/logidze_logger.sql [hunk 2]
```diff
@@ -89,11 +89,25 @@ CREATE OR REPLACE FUNCTION logidze_logger() RETURNS TRIGGER AS $body$
...
+            changes = row_to_json(NEW.*)::jsonb;
```
Comment (palkan) [inline lib/generators/logidze/install/functions/logidze_logger.sql:96]: Don't we need to stringify object values? Like we do here:https://github.com/palkan/logidze/blob/3521c5f26b0803cd06c541f0fd6524e2380bff27/lib/generators/logidze/install/functions/logidze_snapshot.sql#L19

Otherwise that wouldn't be compatible with hstore version.

**Comment by skryukov** [comment]
@bf4 hope you'll check this out =)

File: lib/generators/logidze/install/functions/logidze_logger.sql [hunk 3]
```diff
@@ -145,6 +180,30 @@ CREATE OR REPLACE FUNCTION logidze_logger() RETURNS TRIGGER AS $body$
...
+      err_jsonb := jsonb_build_object(
+        'returned_sqlstate', err_sqlstate,
+        'message_text', err_message,
+        'pg_exception_detail', err_detail,
+        'pg_exception_hint', err_hint,
+        'pg_exception_context', err_context,
+        'schema_name', err_schema_name,
+        'table_name', err_table_name
+      );
+      err_captured = logidze_capture_exception(err_jsonb);
```
Comment (bf4) [inline lib/generators/logidze/install/functions/logidze_logger.sql:201]: ooooh

File: lib/generators/logidze/install/functions/logidze_capture_exception.sql [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+  --   - pg_exception_detail
+  --   - pg_exception_hint
+  --   - pg_exception_context
+  --   - schema_name
+  --   - table_name
+  -- Learn more about available keys:
+  -- https://www.postgresql.org/docs/9.6/plpgsql-control-structures.html#PLPGSQL-EXCEPTION-DIAGNOSTICS-VALUES
+  --
+  RAISE USING ERRCODE = error_data->>'returned_sqlstate',
+    MESSAGE = error_data->>'message_text'
```
Comment (bf4) [inline lib/generators/logidze/install/functions/logidze_capture_exception.sql:20]: interesting.

File: bench/triggers/hstore_with_fallback_setup.sql [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+      changes_h := hstore_to_jsonb_loose(
+        hstore(NEW.*) - hstore(OLD.*)
+      );
+    EXCEPTION
+      WHEN OTHERS THEN
+        changes_h := (SELECT
+          COALESCE(json_object_agg(key, value), '{}')::jsonb
+          FROM
+          jsonb_each(row_to_json(NEW.*)::jsonb)
+          WHERE NOT jsonb_build_object(key, value) <@ row_to_json(OLD.*)::jsonb);
```
Comment (bf4) [inline bench/triggers/hstore_with_fallback_setup.sql:19]: 👍

File: lib/generators/logidze/install/functions/logidze_logger.sql [hunk 6]
```diff
@@ -89,11 +98,37 @@ CREATE OR REPLACE FUNCTION logidze_logger() RETURNS TRIGGER AS $body$
...
+        BEGIN
+          changes = hstore_to_jsonb_loose(hstore(NEW.*));
+        EXCEPTION
+          WHEN NUMERIC_VALUE_OUT_OF_RANGE THEN
+            changes = row_to_json(NEW.*)::jsonb;
+            FOR k IN (SELECT key FROM jsonb_each(changes))
+            LOOP
+              IF jsonb_typeof(changes->k) = 'object' THEN
+                changes = jsonb_set(changes, ARRAY[k], to_jsonb(changes->>k));
+              END IF;
```
Comment (bf4) [inline lib/generators/logidze/install/functions/logidze_logger.sql:110]: 👍

File: lib/generators/logidze/install/functions/logidze_capture_exception.sql (hunk 4 above)
Comment (skryukov) [reply lib/generators/logidze/install/functions/logidze_capture_exception.sql]: Oops, I just removed it, `logidze_capture_exception` will be an empty function that returns false by default.

**Review by palkan — APPROVED** [review]
Awesome! Thanks!

We only need to update the docs and add a change log entry.

File: lib/generators/logidze/install/functions/logidze_capture_exception.sql [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+  -- `error_data` contains:
+  --   - returned_sqlstate
+  --   - message_text
+  --   - pg_exception_detail
+  --   - pg_exception_hint
+  --   - pg_exception_context
+  --   - schema_name
+  --   - table_name
+  -- Learn more about available keys:
+  -- https://www.postgresql.org/docs/9.6/plpgsql-control-structures.html#PLPGSQL-EXCEPTION-DIAGNOSTICS-VALUES
```
Comment (bf4) [inline lib/generators/logidze/install/functions/logidze_capture_exception.sql:17]: to your mind, how might error handling different when `(coalesce(current_setting('logidze.full_snapshot', true), '') = 'on')`? Asking since it's used in the caller and available in this context, though not explicitly passed in.

File: lib/generators/logidze/install/functions/logidze_logger.sql [hunk 8]
```diff
@@ -9,13 +9,22 @@ CREATE OR REPLACE FUNCTION logidze_logger() RETURNS TRIGGER AS $body$
     history_limit integer;
     debounce_time integer;
     current_version integer;
-    merged jsonb;
```
Comment (bf4) [inline lib/generators/logidze/install/functions/logidze_logger.sql:12]: merged wasn't used?

Comment (skryukov) [reply lib/generators/logidze/install/functions/logidze_logger.sql:12]: yep, `merged` was extracted to `logidze_compact_history`, but decloration left: https://github.com/palkan/logidze/commit/5129ea350ace214d76627ec8dee1e69af489121d

File: CHANGELOG.md [hunk 9]
```diff
@@ -2,6 +2,13 @@
 
 ## master (unreleased)
 
+- Add user-defined exception handling ([@skryukov][])
+
+By default, Logidze raises an exception which causes the entire transaction to fail.
+To change this behavior, it's now possible to override `logidze_capture_exception(error_data jsonb)` function. 
+
+- [Fixes [#69](https://github.com/palkan/logidze/issues/69)] Fallback on NUMERIC_VALUE_OUT_OF_RANGE exception ([@skryukov][])
```
Comment (bf4) [inline CHANGELOG.md:10]: There's a command to run to migrate the function, right?

```
bundle exec rails generate logidze:install --update
```

(assuming the pending migration warning is off)

https://github.com/palkan/logidze/blob/ad858c99a130ce4efa610e642d352d0cb8d03aaf/README.md#upgrading

Comment (skryukov) [reply CHANGELOG.md:10]: Yes, that's it. You should also run `bundle exec rails db:migrate` then =)

File: lib/generators/logidze/install/functions/logidze_capture_exception.sql (hunk 7 above)
Comment (skryukov) [reply lib/generators/logidze/install/functions/logidze_capture_exception.sql:17]: Honestly didn't understand your thought. How is the setting should affect this "global" error handler?

File: README.md [hunk 10]
```diff
@@ -544,11 +544,14 @@ First, when restoring data dumps you should consider using `--disable-triggers`
 
 When restoring data dumps for a particular PostgreSQL schema (e.g., when using Apartment), you may encounter the issue with non-existent Logidze functions. That happens because `pg_dump` adds `SELECT pg_catalog.set_config('search_path', '', false);`, and, thus, breaks our existing triggers/functions, because they live either in "public" or in a tenant's namespace (see [this thread](https://postgrespro.com/list/thread-id/2448092)).
 
-### `PG::NumericValueOutOfRange: ERROR: value overflows numeric format`
```
[the remark this answers is not in the document]
Comment (skryukov) [reply README.md]: Done

File: lib/generators/logidze/install/functions/logidze_capture_exception.sql (hunk 7 above)
Comment (bf4) [reply lib/generators/logidze/install/functions/logidze_capture_exception.sql:17]: Here's my thought process.

1. logidze_logger is called
2. `IF (coalesce(current_setting('logidze.full_snapshot', true), '') = 'on') THEN` save log
3. `ELSE` save log
4. EXCEPTION (non-NUMERIC_VALUE_OUT_OF_RANGE) then `logidze_capture_exception(err_jsonb)`


I noticed that there are two possible paths to save log data and the error handler doesn't pass in the distinguishing condition between the two paths (logidze.full_snapshot). 

It's also not obvious to me how the handler might need to behave differently depending on which branch raised the exception, but I thought it worth asking since you have a better understanding of the library (and probably pg in general) than I do.

From your answer I infer it's unlikely to make a difference in error handling.

Comment (skryukov) [reply lib/generators/logidze/install/functions/logidze_capture_exception.sql:17]: Thanks for the clarification =) I think one can check setting `(coalesce(current_setting('logidze.full_snapshot', true), '') = 'on')` in the error handler, so it should do the trick.

**Comment by bf4** [comment]
Anything blocking cutting a new release?

**Comment by palkan** [comment]
> Anything blocking cutting a new release?

Yeah, me)) I haven't had time to review #195, and I want to include it into the next release.

Hopefully, I granted @skryukov an access to releasing; so, that wouldn't become a problem again)

**Comment by bf4** [comment]
Excited to try this out!

```
bundle exec rails generate logidze:install --update
bundle exec rails db:migrate
```

running tests.. :)
