### PR TITLE
fix: support JSON columns

### LINKED ISSUE #209: Tracking changes on JSONB column error
### Tell us about your environment

**Ruby Version:** 3.1.2

**Rails Version:** 7.0.2.3

**PostgreSQL Version:** 13.2

**Logidze Version:** 1.2.1

### What did you do?
I have model:
```
  create_table "document_datum", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.uuid "document_id", null: false
    t.json "data", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["document_id"], name: "index_document_datum_on_document_id"
  end
```
```
dd =  DocumentData.create!(document_id: "af34c215-8c50-42d3-a52b-67a8ca8354a1", data: {test: 1})
dd.update!(data: {test: 2})
```
### What did you expect to happen?
Change JSON column data and log it.

### What actually happened?
```
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  could not identify an equality operator for type json
CONTEXT:  PL/pgSQL function logidze_logger() line 73 at IF
```

Column data is changed, but log_data is same.

### PR DESCRIPTION
**Pull request by baygeldin**
### What is the purpose of this pull request?
Fixes #209.

### What changes did you make? (overview)
I don't think it's a good idea to create a custom comparison operator for a built-in type (also it wouldn't work in this case anyway), so I think casting pseudorecords to JSONB before comparing them is a better workaround.

### Is there anything you'd like reviewers to focus on?
Honestly, a better solution would be to use JSONB over JSON in most cases. So chances of running into this issue are pretty low, but a bug is a bug.

### Checklist

- [x] I've added tests for this change
- [ ] I've added a Changelog entry
- [ ] I've updated a documentation (Readme)

### CODE REVIEW

File: lib/generators/logidze/install/functions/logidze_logger.sql [hunk 1]
```diff
@@ -70,7 +70,7 @@ CREATE OR REPLACE FUNCTION logidze_logger() RETURNS TRIGGER AS $body$
         END IF;
       END IF;
 
-      IF NEW = OLD THEN
```
Comment (palkan) [inline lib/generators/logidze/install/functions/logidze_logger.sql:73]: It would be great to see the performance difference of introducing this conversion; maybe, we can run our benchmarks? (See the `bench/` folder)

We can apply a kind of deoptimization here: 

```sql
BEGIN
  IF NEW = OLD THEN
    return NEW;
  END IF;
EXCEPTION
  WHEN <whatever it is> THEN
     IF to_jsonb(NEW.*) = to_jsonb(OLD.*) THEN
       RETURN NEW;
     END IF';
END;
````

(And we should also check if there is a noticeable performance degradation)

**Review by palkan — CHANGES_REQUESTED** [review]

File: lib/generators/logidze/install/functions/logidze_logger.sql (hunk 1 above)
Comment (baygeldin) [reply lib/generators/logidze/install/functions/logidze_logger.sql:73]: So, I've updated the benchmarks, and the results seem to be similar for all of the options (when running `benchmarks/update_bench.rb`).

Original implementation (with JSONB `dump` column instead of JSON in order to avoid the error):
```
Generating 1000 records... Done in 31.6806233s
Warming up --------------------------------------
     Plain UPDATE #1    11.000  i/100ms
        PT UPDATE #1     8.000  i/100ms
   Logidze UPDATE #1    11.000  i/100ms
Calculating -------------------------------------
     Plain UPDATE #1    192.704  (±29.1%) i/s -    902.000  in   5.006673s
        PT UPDATE #1    119.735  (±33.4%) i/s -    560.000  in   5.047500s
   Logidze UPDATE #1    161.817  (±24.7%) i/s -    770.000  in   5.041253s

Comparison:
     Plain UPDATE #1:      192.7 i/s
   Logidze UPDATE #1:      161.8 i/s - same-ish: difference falls within error
        PT UPDATE #1:      119.7 i/s - same-ish: difference falls within error

Warming up --------------------------------------
     Plain UPDATE #2     6.000  i/100ms
        PT UPDATE #2     4.000  i/100ms
   Logidze UPDATE #2     5.000  i/100ms
Calculating -------------------------------------
     Plain UPDATE #2     83.782  (±27.5%) i/s -    402.000  in   5.065633s
        PT UPDATE #2     53.830  (±26.0%) i/s -    260.000  in   5.046071s
   Logidze UPDATE #2     80.952  (±48.2%) i/s -    370.000  in   5.047402s

Comparison:
     Plain UPDATE #2:       83.8 i/s
   Logidze UPDATE #2:       81.0 i/s - same-ish: difference falls within error
        PT UPDATE #2:       53.8 i/s - same-ish: difference falls within error
```

With casting to JSONB:
```
Generating 1000 records... Done in 32.0015556s
Warming up --------------------------------------
     Plain UPDATE #1    11.000  i/100ms
        PT UPDATE #1     8.000  i/100ms
   Logidze UPDATE #1    10.000  i/100ms
Calculating -------------------------------------
     Plain UPDATE #1    178.512  (±29.7%) i/s -    825.000  in   5.003882s
        PT UPDATE #1    123.008  (±26.8%) i/s -    584.000  in   5.047852s
   Logidze UPDATE #1    155.165  (±25.8%) i/s -    740.000  in   5.055674s

Comparison:
     Plain UPDATE #1:      178.5 i/s
   Logidze UPDATE #1:      155.2 i/s - same-ish: difference falls within error
        PT UPDATE #1:      123.0 i/s - same-ish: difference falls within error

Warming up --------------------------------------
     Plain UPDATE #2     5.000  i/100ms
        PT UPDATE #2     4.000  i/100ms
   Logidze UPDATE #2     5.000  i/100ms
Calculating -------------------------------------
     Plain UPDATE #2     89.237  (±51.5%) i/s -    400.000  in   5.046479s
        PT UPDATE #2     53.057  (±28.3%) i/s -    252.000  in   5.004583s
   Logidze UPDATE #2     77.411  (±28.4%) i/s -    365.000  in   5.001165s

Comparison:
     Plain UPDATE #2:       89.2 i/s
   Logidze UPDATE #2:       77.4 i/s - same-ish: difference falls within error
        PT UPDATE #2:       53.1 i/s - same-ish: difference falls within error
```

With casting to JSONB only in case of an error:
```
Generating 1000 records... Done in 31.6082378s
Warming up --------------------------------------
     Plain UPDATE #1    10.000  i/100ms
        PT UPDATE #1     8.000  i/100ms
   Logidze UPDATE #1    10.000  i/100ms
Calculating -------------------------------------
     Plain UPDATE #1    181.856  (±31.3%) i/s -    840.000  in   5.026085s
        PT UPDATE #1    123.663  (±27.5%) i/s -    584.000  in   5.040383s
   Logidze UPDATE #1    159.170  (±22.0%) i/s -    760.000  in   5.004458s

Comparison:
     Plain UPDATE #1:      181.9 i/s
   Logidze UPDATE #1:      159.2 i/s - same-ish: difference falls within error
        PT UPDATE #1:      123.7 i/s - same-ish: difference falls within error

Warming up --------------------------------------
     Plain UPDATE #2     5.000  i/100ms
        PT UPDATE #2     4.000  i/100ms
   Logidze UPDATE #2     5.000  i/100ms
Calculating -------------------------------------
     Plain UPDATE #2     82.446  (±27.9%) i/s -    390.000  in   5.006902s
        PT UPDATE #2     54.852  (±23.7%) i/s -    264.000  in   5.050243s
   Logidze UPDATE #2     74.415  (±24.2%) i/s -    355.000  in   5.002545s

Comparison:
     Plain UPDATE #2:       82.4 i/s
   Logidze UPDATE #2:       74.4 i/s - same-ish: difference falls within error
        PT UPDATE #2:       54.9 i/s - same-ish: difference falls within error
```

Here's the SQL code I used for the last option (for reference):
```sql
BEGIN
	IF NEW = OLD THEN
		RETURN NEW;
	END IF;
EXCEPTION
	WHEN undefined_function THEN
		IF to_jsonb(NEW.*) = to_jsonb(OLD.*) THEN
			RETURN NEW;
		END IF;
END;
```

File: bench/performance/benchmarks/update_bench.rb [hunk 2]
```diff
@@ -41,15 +43,21 @@ class LogidzeUser
...
+    user = PaperTrailUser.random
+    user.update!(params2.except(*JSON_COLUMNS))
+    user.update!(params2.slice(*JSON_COLUMNS))
   end
 
   x.report("Logidze UPDATE #2") do
-    LogidzeUser.random.update!(params2)
+    user = LogidzeUser.random
+    user.update!(params2.except(*JSON_COLUMNS))
+    user.update!(params2.slice(*JSON_COLUMNS))
```
Comment (baygeldin) [inline bench/performance/benchmarks/update_bench.rb:60]: As for why this change is needed: I didn't dig deep, but the error doesn't appear when we update multiple columns at once (the JSON and JSONB columns are saved as strings in `log_data` column, but apart from that everythin works as expected). However, if we update only JSON and JSONB columns, the error can be reproduced.

**Comment by fameoflight** [comment]
I know it's asking too much, but how would I implement if I just want to track if the json was updated or not, not the actual content. Or only one of the keys in jsonb

File: lib/generators/logidze/install/functions/logidze_logger.sql (hunk 1 above)
Comment (palkan) [reply lib/generators/logidze/install/functions/logidze_logger.sql:73]: > Let's bump the version for this SQL

@baygeldin ping

Comment (baygeldin) [reply lib/generators/logidze/install/functions/logidze_logger.sql:73]: Sorry, this PR completely slipped my mind. I've updated the version in the beginning of the file (what's its purpose btw?). I can also revert changes to benchmarks that were needed to compare different implementations if it's needed.

Comment (baygeldin) [reply lib/generators/logidze/install/functions/logidze_logger.sql:73]: Oh, I see, thought it was just a comment initially.
